@startuml

actor "Player" as player
node "Server" as server

rectangle "Barre d'outils"{

   (Gestion affichage conteneur) as Show
   (Afficher toutes les unités possible en fonction du joueur) as U0
   (Voir quel joueur à cliqué) as U1
   (Détecter sa faction) as U2
   (Lister les unités possible) as U3

}

@enduml