@startuml "Usecase_mainGame"

actor "Joueur" as Player
node "Serveur" as Server
node "Socket.io" as So
database "Database" as BD

rectangle "Jeu principale" {
   (Connecter trois joueurs ensemble) as Connect
   (Accéder à la barre d'outil) as T0
   (Construire nouveaux batiments) as T1
   (Recruter des unités) as T2
   (Gestion des unités) as U0
   (Selectionner une unité) as U1
   (Déplacer une unité) as U2
   (Collecter données unités) as U3
   (Gestions de l'asyncronisme) as A0
   (Envoyez des messages) as A1
   (Recevoir des messages) as A2
   (Traiter les messages) as A3
   (Gestion d'un chat instantanée) as C0
   (Envoie de message) as C1
   (Reception de message) as C2
   (Visionner l'assyncronisme) as AV0
}

Server --> So <<include>>
Server --> BD <<include>>
Server --> Connect

Player --> T0
Player --> U0
Player --> A0

T0 --> T1 <<include>>
T0 --> T2 <<include>>
T0 --> AV0 <<include>>

U0 --> U1 <<include>>
U0 --> U2 <<include>>
U0 --> U3 <<include>>

A0 --> A1 <<include>>
A0 --> A2 <<include>>
A0 --> A3 <<include>>
A0 --> AV0 <<include>>

Server --> A0
Server --> U3

Player --> C0
Server --> C0
C0 --> C1 <<include>>
C0 --> C2 <<include>>



@endulm
